name: docsify Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: master

      - name: generate sidebar
        run: |
          python autoSidebar.py

      - name: Deploy to vps
        uses: contention/rsync-deployments@v1.0.0
        env: 
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
        with: 
          args: "-avzr --delete  jyf@www.wycjyf.live:/var/www/docsify/"
