name: docsify Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Deploy to vps
        uses: contention/rsync-deployments@v1.0.0
        env: 
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
        with: 
          args: "-avzr --delete  jyf@www.wycjyf.live:/var/www/docsify/"
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan www.wycjyf.live >> ~/.ssh/known_hosts
          git config --global user.email "jyfserendipity@outlook.com"
          git config --global user.name "jyf-111"

          mkdir -p source/_port/
          mv !(source|scaffolds|.git|.github|*.md|*.py|.nojekyll|index.html) source/_port/

          npm install hexo-cli -g
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo generate
          hexo deploy
